version: '3.8'

services:
  nest_app:
    build: ./server
    ports:
      - 3001:3001
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/myDatabase

  next_app:
    build: ./client
    ports:
      - 3002:3002
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
