version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-seed:/docker-entrypoint-initdb.d
  server_app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017
      - CORS_ORIGIN=http://localhost:3002
    depends_on:
      - mongo
  next_app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - server_app
volumes:
  mongo-data:
    driver: local
